apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green
spec:
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: iwanariy/sampleapp:green
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  type: LoadBalancer
  selector:
    app: green
  ports:
  - name: green
    port: 8080
    targetPort: 8080
