apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userservice
spec:
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: k8s.gcr.io/serve_hostname:v1.4
        ports:
        - containerPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: LoadBalancer
  selector:
    app: userservice
  ports:
  - name: userservice
    port: 80
    targetPort: 9376
